import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import Swal from 'sweetalert2';
import withReactContent from 'sweetalert2-react-content';
import './App.css';
import './Form.css';

const MySwal = withReactContent(Swal);

export default function BlogGenerator() {
    const [title, setTitle] = useState('');
    const [keywords, setKeywords] = useState('');
    const [tone, setTone] = useState('Casual');
    const [wordLimit, setWordLimit] = useState(500);
    const [loading, setLoading] = useState(false);
    const navigate = useNavigate();

    async function generateBlog(ev) {
        ev.preventDefault();
        setLoading(true);

        try {
            const response = await fetch(`${process.env.REACT_APP_API_URL}/generate-blog`, {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                },
                body: JSON.stringify({ title, keywords, tone, wordLimit }),
            });

            if (response.ok) {
                const data = await response.json();
                MySwal.fire({
                    title: 'Generated!',
                    text: 'Blog draft generated successfully. Redirecting to editor...',
                    icon: 'success',
                    timer: 2000,
                    showConfirmButton: false
                });

                // Navigate to CreatePost with state
                navigate('/create', {
                    state: {
                        title: title,
                        content: data.content,
                        summary: `Draft generated by AI with keywords: ${keywords}`
                    }
                });
            } else {
                const errData = await response.json();
                throw new Error(errData.error || 'Failed to generate');
            }
        } catch (err) {
            MySwal.fire({
                title: 'Error',
                text: err.message || 'Failed to generate blog post. Check API Key.',
                icon: 'error'
            });
        } finally {
            setLoading(false);
        }
    }

    return (
        <div className="center createpost">
            <h1>AI BLOG GENERATOR</h1>
            <form onSubmit={generateBlog}>
                <div className="inputbox">
                    <input
                        type="text"
                        value={title}
                        onChange={ev => setTitle(ev.target.value)}
                        required
                    />
                    <span>Title</span>
                </div>

                <div className="inputbox">
                    <input
                        type="text"
                        value={keywords}
                        onChange={ev => setKeywords(ev.target.value)}
                        required
                    />
                    <span>Keywords (comma separated)</span>
                </div>

                <div className="inputbox" style={{ marginBottom: '20px' }}>
                    {/* Using a select for tone. Styling to match the dark theme looks */}
                    <label style={{ display: 'block', marginBottom: '5px', color: '#aaa', fontSize: '0.8rem' }}>Tone</label>
                    <select
                        value={tone}
                        onChange={ev => setTone(ev.target.value)}
                        style={{
                            width: '100%',
                            padding: '10px',
                            background: 'transparent',
                            color: '#fff',
                            border: '1px solid #fff',
                            borderRadius: '5px'
                        }}
                    >
                        <option value="Casual" style={{ color: 'black' }}>Casual</option>
                        <option value="Formal" style={{ color: 'black' }}>Formal</option>
                        <option value="Technical" style={{ color: 'black' }}>Technical</option>
                    </select>
                </div>

                <div className="inputbox">
                    <input
                        type="number"
                        value={wordLimit}
                        onChange={ev => setWordLimit(ev.target.value)}
                        required
                        min="100"
                        max="2000"
                    />
                    <span>Word Limit</span>
                </div>

                <div className="buttons btn">
                    <button className="blob-btn" disabled={loading}>
                        {loading ? 'Generating...' : 'Generate Draft'}
                        <span className="blob-btn__inner">
                            <span className="blob-btn__blobs">
                                <span className="blob-btn__blob"></span>
                                <span className="blob-btn__blob"></span>
                                <span className="blob-btn__blob"></span>
                                <span className="blob-btn__blob"></span>
                            </span>
                        </span>
                    </button>
                    <br />
                    <svg xmlns="http://www.w3.org/2000/svg" version="1.1">
                        <defs>
                            <filter id="goo">
                                <feGaussianBlur in="SourceGraphic" result="blur" stdDeviation="10"></feGaussianBlur>
                                <feColorMatrix in="blur" mode="matrix" values="1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 21 -7" result="goo"></feColorMatrix>
                                <feBlend in2="goo" in="SourceGraphic" result="mix"></feBlend>
                            </filter>
                        </defs>
                    </svg>
                </div>
            </form>
        </div>
    );
}
