import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { apiFetch } from '../utils/api';
import BlobButton from '../components/BlobButton';
import '../styles/App.css';
import '../styles/Form.css';
import Swal from 'sweetalert2';
import withReactContent from 'sweetalert2-react-content';

const MySwal = withReactContent(Swal);

export default function BlogGenerator() {
    const [title, setTitle] = useState('');
    const [keywords, setKeywords] = useState('');
    const [tone, setTone] = useState('Casual');
    const [wordLimit, setWordLimit] = useState(500);
    const [loading, setLoading] = useState(false);
    const navigate = useNavigate();

    async function generateBlog(ev) {
        ev.preventDefault();
        setLoading(true);
        try {
            const response = await apiFetch('/generate-blog', {
                method: 'POST',
                body: JSON.stringify({ title, keywords, tone, wordLimit }),
            });

            if (response.ok) {
                const data = await response.json();
                MySwal.fire({ title: 'Generated!', text: 'Blog draft generated. Redirecting to editor...', icon: 'success', timer: 2000, showConfirmButton: false });
                navigate('/create', {
                    state: { title, content: data.content, summary: `Draft generated by AI with keywords: ${keywords}` },
                });
            } else {
                const errData = await response.json();
                throw new Error(errData.error || 'Failed to generate');
            }
        } catch (err) {
            MySwal.fire({ title: 'Error', text: err.message || 'Failed to generate blog post. Check API Key.', icon: 'error' });
        } finally {
            setLoading(false);
        }
    }

    return (
        <div className="center createpost">
            <h1>AI BLOG GENERATOR</h1>
            <form onSubmit={generateBlog}>
                <div className="inputbox">
                    <input type="text" value={title} onChange={ev => setTitle(ev.target.value)} required />
                    <span>Title</span>
                </div>
                <div className="inputbox">
                    <input type="text" value={keywords} onChange={ev => setKeywords(ev.target.value)} required />
                    <span>Keywords (comma separated)</span>
                </div>
                <div className="inputbox" style={{ marginBottom: '20px' }}>
                    <label style={{ display: 'block', marginBottom: '5px', color: '#aaa', fontSize: '0.8rem' }}>Tone</label>
                    <select value={tone} onChange={ev => setTone(ev.target.value)} style={{ width: '100%', padding: '10px', background: 'transparent', color: '#fff', border: '1px solid #fff', borderRadius: '5px' }}>
                        <option value="Casual" style={{ color: 'black' }}>Casual</option>
                        <option value="Formal" style={{ color: 'black' }}>Formal</option>
                        <option value="Technical" style={{ color: 'black' }}>Technical</option>
                    </select>
                </div>
                <div className="inputbox">
                    <input type="number" value={wordLimit} onChange={ev => setWordLimit(ev.target.value)} required min="100" max="2000" />
                    <span>Word Limit</span>
                </div>
                <BlobButton type="submit" disabled={loading} className="btn">
                    {loading ? 'Generating...' : 'Generate Draft'}
                </BlobButton>
            </form>
        </div>
    );
}
